N: "1.0"
lambda: "1.0"
pv: "0.2"
alpha: "3.0"
beta: "1.5"
yita: "1,3,5,7,9"
yitami: "-1"
nn: "0.01,0.1,0.5,1,2,4,6,8,10"
nnmi: "3"
k: "30"
maxPosX: "100"
maxPosY: "100"
receiveR: "30"
nodeNumber: "300"
timeSlot: "4"
simulationTimes: "20"
